# including default.yaml
defaults:
  - default
  - _self_

agent_workflow: "mixture-of-agents"

workflow_args:
  num_rounds: 2
  template_id: 0
  shuffle_responses: true

chat_template:
  - "$question\n\nPlease reason step by step, and put your final answer within \\boxed{}."
agents:
  - generator_1:
      role: generator
  - generator_2:
      role: generator
  - aggregator:
      role: aggregator
      chat_template:
        - "You are the top decision-maker. Good at analyzing and summarizing mathematical problems, judging and summarizing other people's solutions, and giving final answers to math problems. You will be given a math problem, analysis and code from other agents. Please find the most reliable answer based on the analysis and results of other agents. Give reasons for making decisions. The last line of your output contains only the final result without any units, for example: The answer is 140.\n\nProblem: $question\n\nHere are solutions from other agents:\n$responses_str"
