# including default.yaml
defaults:
  - default
  - _self_

agent_workflow: "chain-of-agents"
async_workflow: false
workflow_func_path: null
processor_func_path: null

workflow_args:
  num_rounds: 1

api_model_name: "gpt-4o"
api_key: null
api_base_url: https://api.openai.com/v1


agents:
  - agent_prompt_engineer:
      role: agent_prompt_engineer
      is_api_model: false
      chat_template: "You are a great prompt engineer, please write a clear prompt for the given question to the planner. Question: {question}"
  - agent_planner:
      role: agent_planner
      is_api_model: true
      model_name: "gpt-4o"
      chat_template: "Task: Produce an execution plan to answer the prompt. You need to refactor the problem into atomic steps for the generator. If external knowledge is needed, wrap what to retrieve in <retrieval></retrieval> and intended usage in <target></target>. Question: {question}, Prompt: {prompt}"
  - agent_retriever:
      role: agent_retriever
      is_api_model: false
      chat_template: "You are a retrieval-oriented answer generator. For any needed external info inside <retrieval></retrieval> in the plan, design focused queries. Emit EACH query in a <tool_call>{\\n  \"name\": \"search\",\\n  \"arguments\": {\\n    \"query_list\": [\"ONE FOCUSED QUERY STRING\"]\\n  }\\n}</tool_call>. Tool responses will appear between <tool_response> and </tool_response>. You don't need to answer the question, you only need to design the query. Question: {question} Plan: {plan}"
      search_execution: true
  - agent_generator:
      role: agent_generator
      is_api_model: false
      chat_template: "You are a great writer who is good at organizing different information. Based on the retrieved content and their corresponding use in <target> and </target>, generate the response to the question. Question: {question} Plan: {plan} Retrieved Information: {information}"

tools_config:
  max_turns: 2
  num_workers: 120
  enable_metrics: True
  enable_rate_limiting: True
  tools:
    search:
      type: search_r1
      enable_rate_limiting: True
      rate_limit: 50
      timeout: 30
      topk: 3
      base_url: "http://127.0.0.1:8000/retrieval"
      schema_path: "examples/schema/search.json"